// Fases, alternativas e explicações ficam nos dados, fora do motor.
const GAME_DATA={cityName:'Nova República',attributes:[{id:'justice',label:'Justiça'},{id:'wisdom',label:'Sabedoria'},{id:'courage',label:'Coragem'},{id:'temperance',label:'Temperança'},{id:'resources',label:'Recursos'},{id:'stability',label:'Estabilidade'}],phases:[
{id:'founding',number:'I',title:'Fundando a cidade',description:'Você recebeu a responsabilidade de fundar uma nova cidade. Ninguém produz sozinho tudo de que precisa: agricultores, artesãos e construtores dependem uns dos outros.',question:'Qual deve ser o primeiro princípio desta comunidade?',discussion:'Conversem: a cidade existe para satisfazer qualquer desejo ou para tornar possível uma vida em comum?',decision:{id:'cooperation',options:[
{id:'cooperation',label:'Organizar funções diferentes e trocar o que cada pessoa produz.',effects:{justice:8,resources:8,temperance:4,stability:4},explanation:'A cidade nasce da cooperação e da divisão de tarefas. No argumento do Livro II de A República, necessidades humanas levam as pessoas a viver juntas e compartilhar funções.'},
{id:'self',label:'Cada família deve tentar produzir tudo de que precisa.',effects:{stability:3,resources:-4,justice:-2},explanation:'A autonomia parece segura, mas limita a especialização e a troca. A cidade começa quando reconhecemos que pessoas diferentes atendem melhor às necessidades umas das outras.'},
{id:'luxury',label:'Priorizar conforto, luxo e crescimento rápido desde o início.',effects:{resources:8,temperance:-8,stability:-3},explanation:'Desejos ampliados exigem mais recursos e podem criar conflitos. Platão relaciona a expansão dos desejos à necessidade de novos recursos e de guardiões.'}] }},
{id:'producers',number:'II',title:'Os produtores',description:'Agricultores, artesãos, comerciantes e trabalhadores mantêm a cidade. É preciso organizar o trabalho e distribuir o que é produzido.',question:'Como equilibrar contribuição, sustento e reconhecimento?',discussion:'Qual escolha parece eficiente? E qual parece justa para quem realiza o trabalho?',decision:{id:'production',options:[
{id:'exchange',label:'Especializar tarefas e garantir trocas proporcionais entre ofícios.',effects:{resources:7,justice:6,stability:4,temperance:2},explanation:'A especialização permite que cada pessoa se dedique melhor a uma função. No modelo platônico, os produtores sustentam a vida material, mas riqueza não determina quem governa.'},
{id:'equal',label:'Distribuir tudo igualmente, sem considerar funções ou necessidades.',effects:{justice:3,temperance:5,resources:-5,stability:-2},explanation:'A igualdade pode proteger contra privilégios, mas uma regra uniforme nem sempre corresponde a necessidades diferentes. O que significa tratar justamente?'},
{id:'profit',label:'Dar mais poder a quem consegue produzir e acumular mais.',effects:{resources:9,justice:-7,temperance:-5,stability:-3},explanation:'A produção pode crescer, mas a riqueza passa a influenciar o poder. Platão critica uma cidade em que interesses econômicos substituem o bem comum.'}] }},
{id:'guardians',number:'III',title:'Os guardiões',description:'Uma ameaça se aproxima. A cidade precisa de defensores; coragem, porém, deve caminhar com disciplina e compreensão do que merece ser protegido.',question:'Como preparar a defesa sem transformar força em domínio?',discussion:'Que diferença há entre proteger a cidade e controlar seus habitantes?',decision:{id:'defense',options:[
{id:'trained',label:'Formar guardiões disciplinados, corajosos e comprometidos com a cidade.',effects:{courage:8,stability:6,justice:5,wisdom:2},explanation:'Os guardiões representam a parte corajosa da cidade. A formação deve orientar a força para proteção e submetê-la a uma finalidade comum.'},
{id:'citizens',label:'Revezar a defesa entre cidadãos, com controle público das decisões.',effects:{justice:4,stability:2,courage:1,resources:-3},explanation:'A participação amplia o controle coletivo, mas exige coordenação. A escolha permite debater participação e especialização.'},
{id:'force',label:'Dar poderes amplos aos defensores para impor ordem rapidamente.',effects:{courage:5,stability:4,justice:-8,temperance:-4},explanation:'A ordem pode crescer no curto prazo, mas a força sem limites ameaça a justiça. A coragem precisa estar ligada à educação e ao bem comum.'}] }},
{id:'ruler',number:'IV',title:'Quem deve governar?',description:'A cidade precisa escolher quem tomará decisões difíceis. Popularidade, riqueza e força conquistam apoio, mas não garantem conhecimento sobre o que é justo.',question:'Que qualidade deve pesar mais na escolha de quem governa?',discussion:'Antes do voto, defendam uma alternativa. As consequências aparecem só depois da escolha.',decision:{id:'ruler_selection',options:[
{id:'wealthy',label:'A pessoa mais rica: provou capacidade e pode financiar a cidade.',effects:{resources:8,wisdom:-6,justice:-8,stability:-3},explanation:'A riqueza pode oferecer recursos, mas não demonstra conhecimento do bem comum. Platão critica a riqueza como critério de autoridade.'},
{id:'popular',label:'A pessoa mais popular: conhece os desejos e a voz da maioria.',effects:{stability:4,justice:1,wisdom:-4,temperance:-2},explanation:'Ouvir a população importa, mas popularidade não equivale a conhecimento. Platão pergunta se governar exige compreender o que é bom, mesmo quando isso é impopular.'},
{id:'strongest',label:'A pessoa mais forte: pode impor decisões e defender a cidade.',effects:{courage:5,stability:2,justice:-9,wisdom:-6},explanation:'A força pode impor obediência, mas não oferece sabedoria ou justiça. Governar não deveria ser mera disputa por poder.'},
{id:'philosopher',label:'A pessoa formada na filosofia, preparada para buscar conhecimento e governar com prudência.',effects:{wisdom:12,justice:9,stability:6,temperance:3},explanation:'Esta opção se aproxima da proposta do filósofo-rei: governar requer formação filosófica e orientação pelo conhecimento do bem. A ideia também permite discutir como impedir que a alegação de “conhecer o bem” se torne autoritária.'}] }}
]};
