// Etapas finais adicionadas sem acoplar novos conteúdos ao motor.
GAME_DATA.phases.push(
 {id:'education',number:'V',title:'Educação para governar',description:'A cidade precisa formar guardiões e futuros governantes. Educação aqui significa transformar desejos, hábitos e entendimento — uma preparação para agir bem, não apenas acumular informações.',question:'Como formar quem terá responsabilidades públicas?',discussion:'A formação deve desenvolver conhecimento e caráter. Como equilibrar ambos?',decision:{id:'education_path',options:[
  {id:'broad_education',label:'Combinar música, exercício, diálogo e estudo gradual.',effects:{wisdom:7,courage:3,temperance:5,justice:3,resources:-3},build:'education',explanation:'A formação platônica inclui cuidado do caráter e do corpo, além do desenvolvimento intelectual. Governar exige uma trajetória educativa prolongada.'},
  {id:'technical_training',label:'Priorizar treinamento técnico e eficiência administrativa.',effects:{resources:5,wisdom:2,temperance:-2,justice:1},build:'education',explanation:'A técnica pode tornar a cidade eficiente, mas não responde sozinha à pergunta sobre fins justos. Conhecer meios não garante saber para que usá-los.'},
  {id:'open_debate',label:'Criar espaços públicos de debate e revisão das decisões.',effects:{wisdom:4,justice:5,stability:-2,temperance:2},build:'education',explanation:'O diálogo ajuda a examinar opiniões e razões. A proposta se relaciona ao papel da investigação filosófica, embora exija tempo e disposição para rever certezas.'}] }},
 {id:'crisis',number:'VI',title:'Crises da cidade',description:'A República enfrenta tensões entre riqueza, poder e desejos particulares. Nenhuma decisão elimina todos os custos; a turma precisa escolher o que proteger primeiro.',question:'Um grupo influente pede que as regras favoreçam seus próprios interesses. Como responder?',discussion:'Considerem os efeitos de curto prazo e o princípio que a cidade deseja preservar.',decision:{id:'crisis_of_interest',options:[
  {id:'rule_of_law',label:'Aplicar regras comuns e abrir a decisão ao exame público.',effects:{justice:6,wisdom:3,stability:2,resources:-2},build:'crisis',explanation:'Regras compartilhadas reduzem o risco de poder virar privilégio. A cidade justa precisa perguntar se cada parte cumpre sua função em harmonia.'},
  {id:'pragmatic_deal',label:'Aceitar parte do pedido para evitar uma ruptura imediata.',effects:{stability:5,resources:3,justice:-4,temperance:-2},build:'crisis',explanation:'O acordo pode conter uma crise presente, mas abre espaço para interesses particulares. É um conflito entre estabilidade imediata e justiça duradoura.'},
  {id:'forceful_response',label:'Impedir o grupo pela força e encerrar a disputa rapidamente.',effects:{courage:3,stability:1,justice:-6,temperance:-3},build:'crisis',explanation:'A resposta pode parecer firme, mas silenciar uma disputa não resolve sua causa. Força sem prudência pode desorganizar a cidade que pretende proteger.'}] }},
 {id:'result',type:'result',number:'VII',title:'República concluída'},
 {id:'cave',type:'cave',number:'VIII',title:'A Alegoria da Caverna'}
);
